export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL'

export const ALL_PRODUCTS_PAGINATION_REQUEST = 'ALL_PRODUCTS_PAGINATION_REQUEST'
export const ALL_PRODUCTS_PAGINATION_SUCCESS = 'ALL_PRODUCTS_PAGINATION_SUCCESS'
export const ALL_PRODUCTS_PAGINATION_FAIL = 'ALL_PRODUCTS_PAGINATION_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'