export const ALL_ADVERTISEMENTS_REQUEST = 'ALL_ADVERTISEMENTS_REQUEST';
export const ALL_ADVERTISEMENTS_SUCCESS = 'ALL_ADVERTISEMENTS_SUCCESS';
export const ALL_ADVERTISEMENTS_FAIL = 'ALL_ADVERTISEMENTS_FAIL';

export const ALL_ADVERTISEMENTS_PAGINATION_REQUEST =
  'ALL_ADVERTISEMENTS_PAGINATION_REQUEST';
export const ALL_ADVERTISEMENTS_PAGINATION_SUCCESS =
  'ALL_ADVERTISEMENTS_PAGINATION_SUCCESS';
export const ALL_ADVERTISEMENTS_PAGINATION_FAIL =
  'ALL_ADVERTISEMENTS_PAGINATION_FAIL';

export const NEW_ADVERTISEMENT_REQUEST = 'NEW_ADVERTISEMENT_REQUEST';
export const NEW_ADVERTISEMENT_SUCCESS = 'NEW_ADVERTISEMENT_SUCCESS';
export const NEW_ADVERTISEMENT_FAIL = 'NEW_ADVERTISEMENT_FAIL';
export const NEW_ADVERTISEMENT_RESET = 'NEW_ADVERTISEMENT_RESET';

export const UPDATE_ADVERTISEMENT_REQUEST = 'UPDATE_ADVERTISEMENT_REQUEST';
export const UPDATE_ADVERTISEMENT_SUCCESS = 'UPDATE_ADVERTISEMENT_SUCCESS';
export const UPDATE_ADVERTISEMENT_FAIL = 'UPDATE_ADVERTISEMENT_FAIL';
export const UPDATE_ADVERTISEMENT_RESET = 'UPDATE_ADVERTISEMENT_RESET';

export const DELETE_ADVERTISEMENT_REQUEST = 'DELETE_ADVERTISEMENT_REQUEST';
export const DELETE_ADVERTISEMENT_SUCCESS = 'DELETE_ADVERTISEMENT_SUCCESS';
export const DELETE_ADVERTISEMENT_FAIL = 'DELETE_ADVERTISEMENT_FAIL';
export const DELETE_ADVERTISEMENT_RESET = 'DELETE_ADVERTISEMENT_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
