export const ALL_AUTHOR_REQUEST = 'ALL_AUTHOR_REQUEST'
export const ALL_AUTHOR_SUCCESS = 'ALL_AUTHOR_SUCCESS'
export const ALL_AUTHOR_FAIL = 'ALL_AUTHOR_FAIL'

export const AUTHOR_DETAILS_REQUEST = 'AUTHOR_DETAILS_REQUEST'
export const AUTHOR_DETAILS_SUCCESS = 'AUTHOR_DETAILS_SUCCESS'
export const AUTHOR_DETAILS_FAIL = 'AUTHOR_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
