export const ALL_AUTHOR_REQUEST = 'ALL_AUTHOR_REQUEST';
export const ALL_AUTHOR_SUCCESS = 'ALL_AUTHOR_SUCCESS';
export const ALL_AUTHOR_FAIL = 'ALL_AUTHOR_FAIL';

export const ALL_AUTHOR_PAGINATION_REQUEST = 'ALL_AUTHOR_PAGINATION_REQUEST';
export const ALL_AUTHOR_PAGINATION_SUCCESS = 'ALL_AUTHOR_PAGINATION_SUCCESS';
export const ALL_AUTHOR_PAGINATION_FAIL = 'ALL_AUTHOR_PAGINATION_FAIL';

export const AUTHOR_DETAILS_REQUEST = 'AUTHOR_DETAILS_REQUEST';
export const AUTHOR_DETAILS_SUCCESS = 'AUTHOR_DETAILS_SUCCESS';
export const AUTHOR_DETAILS_FAIL = 'AUTHOR_DETAILS_FAIL';

export const NEW_AUTHOR_REQUEST = 'NEW_AUTHOR_REQUEST';
export const NEW_AUTHOR_SUCCESS = 'NEW_AUTHOR_SUCCESS';
export const NEW_AUTHOR_FAIL = 'NEW_AUTHOR_FAIL';
export const NEW_AUTHOR_RESET = 'NEW_AUTHOR_RESET';

export const UPDATE_AUTHOR_REQUEST = 'UPDATE_AUTHOR_REQUEST';
export const UPDATE_AUTHOR_SUCCESS = 'UPDATE_AUTHOR_SUCCESS';
export const UPDATE_AUTHOR_FAIL = 'UPDATE_AUTHOR_FAIL';
export const UPDATE_AUTHOR_RESET = 'UPDATE_AUTHOR_RESET';

export const DELETE_AUTHOR_REQUEST = 'DELETE_AUTHOR_REQUEST';
export const DELETE_AUTHOR_SUCCESS = 'DELETE_AUTHOR_SUCCESS';
export const DELETE_AUTHOR_FAIL = 'DELETE_AUTHOR_FAIL';
export const DELETE_AUTHOR_RESET = 'DELETE_AUTHOR_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
