export const ALL_DISCOUNTS_REQUEST = 'ALL_DISCOUNTS_REQUEST';
export const ALL_DISCOUNTS_SUCCESS = 'ALL_DISCOUNTS_SUCCESS';
export const ALL_DISCOUNTS_FAIL = 'ALL_DISCOUNTS_FAIL';

export const ALL_DISCOUNTS_PAGINATION_REQUEST =
  'ALL_DISCOUNTS_PAGINATION_REQUEST';
export const ALL_DISCOUNTS_PAGINATION_SUCCESS =
  'ALL_DISCOUNTS_PAGINATION_SUCCESS';
export const ALL_DISCOUNTS_PAGINATION_FAIL = 'ALL_DISCOUNTS_PAGINATION_FAIL';

export const NEW_DISCOUNT_REQUEST = 'NEW_DISCOUNT_REQUEST';
export const NEW_DISCOUNT_SUCCESS = 'NEW_DISCOUNT_SUCCESS';
export const NEW_DISCOUNT_FAIL = 'NEW_DISCOUNT_FAIL';
export const NEW_DISCOUNT_RESET = 'NEW_DISCOUNT_RESET';

export const UPDATE_DISCOUNT_REQUEST = 'UPDATE_DISCOUNT_REQUEST';
export const UPDATE_DISCOUNT_SUCCESS = 'UPDATE_DISCOUNT_SUCCESS';
export const UPDATE_DISCOUNT_FAIL = 'UPDATE_DISCOUNT_FAIL';
export const UPDATE_DISCOUNT_RESET = 'UPDATE_DISCOUNT_RESET';

export const DELETE_DISCOUNT_REQUEST = 'DELETE_DISCOUNT_REQUEST';
export const DELETE_DISCOUNT_SUCCESS = 'DELETE_DISCOUNT_SUCCESS';
export const DELETE_DISCOUNT_FAIL = 'DELETE_DISCOUNT_FAIL';
export const DELETE_DISCOUNT_RESET = 'DELETE_DISCOUNT_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
