export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST';
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL';

export const ALL_PRODUCTS_PAGINATION_REQUEST =
  'ALL_PRODUCTS_PAGINATION_REQUEST';
export const ALL_PRODUCTS_PAGINATION_SUCCESS =
  'ALL_PRODUCTS_PAGINATION_SUCCESS';
export const ALL_PRODUCTS_PAGINATION_FAIL = 'ALL_PRODUCTS_PAGINATION_FAIL';

export const ALL_PRODUCTS_PAGINATION_ADMIN_REQUEST =
  'ALL_PRODUCTS_PAGINATION_ADMIN_REQUEST';
export const ALL_PRODUCTS_PAGINATION_ADMIN_SUCCESS =
  'ALL_PRODUCTS_PAGINATION_ADMIN_SUCCESS';
export const ALL_PRODUCTS_PAGINATION_ADMIN_FAIL =
  'ALL_PRODUCTS_PAGINATION_ADMIN_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const SINGLE_REVIEW_PRODUCT_REQUEST = 'SINGLE_REVIEW_PRODUCT_REQUEST';
export const SINGLE_REVIEW_PRODUCT_SUCCESS = 'SINGLE_REVIEW_PRODUCT_SUCCESS';
export const SINGLE_REVIEW_PRODUCT_FAIL = 'SINGLE_REVIEW_PRODUCT_FAIL';

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST';
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS';
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL';
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET';

export const NEW_PRODUCT_REQUEST = 'NEW_PRODUCT_REQUEST';
export const NEW_PRODUCT_SUCCESS = 'NEW_PRODUCT_SUCCESS';
export const NEW_PRODUCT_FAIL = 'NEW_PRODUCT_FAIL';
export const NEW_PRODUCT_RESET = 'NEW_PRODUCT_RESET';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';
export const DELETE_PRODUCT_RESET = 'DELETE_PRODUCT_RESET';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';
export const UPDATE_PRODUCT_RESET = 'UPDATE_PRODUCT_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
