export const ALL_SUB_CATEGORIES_REQUEST = 'ALL_SUB_CATEGORIES_REQUEST';
export const ALL_SUB_CATEGORIES_SUCCESS = 'ALL_SUB_CATEGORIES_SUCCESS';
export const ALL_SUB_CATEGORIES_FAIL = 'ALL_SUB_CATEGORIES_FAIL';

export const ALL_SUB_CATEGORIES_PAGINATION_REQUEST =
  'ALL_SUB_CATEGORIES_PAGINATION_REQUEST';
export const ALL_SUB_CATEGORIES_PAGINATION_SUCCESS =
  'ALL_SUB_CATEGORIES_PAGINATION_SUCCESS';
export const ALL_SUB_CATEGORIES_PAGINATION_FAIL =
  'ALL_SUB_CATEGORIES_PAGINATION_FAIL';

export const NEW_SUB_CATEGORY_REQUEST = 'NEW_SUB_CATEGORY_REQUEST';
export const NEW_SUB_CATEGORY_SUCCESS = 'NEW_SUB_CATEGORY_SUCCESS';
export const NEW_SUB_CATEGORY_FAIL = 'NEW_SUB_CATEGORY_FAIL';
export const NEW_SUB_CATEGORY_RESET = 'NEW_SUB_CATEGORY_RESET';

export const UPDATE_SUB_CATEGORY_REQUEST = 'UPDATE_SUB_CATEGORY_REQUEST';
export const UPDATE_SUB_CATEGORY_SUCCESS = 'UPDATE_SUB_CATEGORY_SUCCESS';
export const UPDATE_SUB_CATEGORY_FAIL = 'UPDATE_SUB_CATEGORY_FAIL';
export const UPDATE_SUB_CATEGORY_RESET = 'UPDATE_SUB_CATEGORY_RESET';

export const DELETE_SUB_CATEGORY_REQUEST = 'DELETE_SUB_CATEGORY_REQUEST';
export const DELETE_SUB_CATEGORY_SUCCESS = 'DELETE_SUB_CATEGORY_SUCCESS';
export const DELETE_SUB_CATEGORY_FAIL = 'DELETE_SUB_CATEGORY_FAIL';
export const DELETE_SUB_CATEGORY_RESET = 'DELETE_SUB_CATEGORY_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
