export const ALL_SUB_CATEGORIES_REQUEST = 'ALL_SUB_CATEGORIES_REQUEST'
export const ALL_SUB_CATEGORIES_SUCCESS = 'ALL_SUB_CATEGORIES_SUCCESS'
export const ALL_SUB_CATEGORIES_FAIL = 'ALL_SUB_CATEGORIES_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'